/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SurveyIndividualImport } from './routes/survey-individual'
import { Route as SurveyImport } from './routes/survey'
import { Route as PricingImport } from './routes/pricing'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SurveyIndividualRoute = SurveyIndividualImport.update({
  id: '/survey-individual',
  path: '/survey-individual',
  getParentRoute: () => rootRoute,
} as any)

const SurveyRoute = SurveyImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyImport
      parentRoute: typeof rootRoute
    }
    '/survey-individual': {
      id: '/survey-individual'
      path: '/survey-individual'
      fullPath: '/survey-individual'
      preLoaderRoute: typeof SurveyIndividualImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/survey': typeof SurveyRoute
  '/survey-individual': typeof SurveyIndividualRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/survey': typeof SurveyRoute
  '/survey-individual': typeof SurveyIndividualRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/survey': typeof SurveyRoute
  '/survey-individual': typeof SurveyIndividualRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pricing' | '/survey' | '/survey-individual'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pricing' | '/survey' | '/survey-individual'
  id: '__root__' | '/' | '/pricing' | '/survey' | '/survey-individual'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  SurveyRoute: typeof SurveyRoute
  SurveyIndividualRoute: typeof SurveyIndividualRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  SurveyRoute: SurveyRoute,
  SurveyIndividualRoute: SurveyIndividualRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pricing",
        "/survey",
        "/survey-individual"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/survey": {
      "filePath": "survey.tsx"
    },
    "/survey-individual": {
      "filePath": "survey-individual.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
